Document = (nl | (dnl)*) Block (dnl Block)* (nl | (dnl)*)
Block = TextContent

<spc> = #'\s'
dnl = #'\n(\n)+'
nl = !dnl #'\n'

TextContent = (charrun | escape | nl | Segment)+

<charrun> = #'[^\n\[\]{}]+'

escape = '\\[' | '\\]' | '\\{' | '\\}'

Segment = '[' tag spc+ Attrs? TextContent ']'

tag = #':[^\s]*'

Attrs = '{' spc* '}'
    | '{' spc* KVPair spc* '}'
    | '{' spc* KVPair (spc+ KVPair)* spc* '}'

KVPair = key spc+ val

key = #':[\w]+'
val = #'[^\s}]+'
