Document = (nl | (dnl)*) Block (dnl Block)* (nl | (dnl)*)
Block = TextContent

<spc> = #'\s'
dnl = #'\n(\n)+'
nl = !dnl #'\n'

TextContent = (charrun | escape | nl | Segment)+

<charrun> = #'[^\n\[\]{}]+'

escape = '\\[' | '\\]' | '\\{' | '\\}'

Segment = '[' tag spc+ attrs? TextContent ']'

tag = #':[^\s]*'

attrs = '{' spc* '}'
    | '{' spc* kvpair spc* '}'
    | '{' spc* kvpair (spc+ kvpair)* spc* '}'

kvpair = key spc+ val

key = #':[\w]+'
val = #'[\w]+'
